### PR TITLE
Add arm targets

### PR DESCRIPTION
**Pull request by jkilpatr**
We use these pretty often, may as well test against them

### CODE REVIEW

**Comment by mpapierski** [comment]
@ttk2 looks good to me BUT for whatever reason the ARM build fails. I wonder whats the problem. I'll investigate it locally, but looks weird: https://travis-ci.com/althea-mesh/clarity/jobs/149553488

```
..qemu: uncaught target signal 11 (Segmentation fault) - core dumped
error: process didn't exit successfully: `qemu-arm /target/arm-unknown-linux-gnueabi/debug/deps/transaction_tests-66d17f6425ac9e3e` (signal: 11, SIGSEGV: invalid memory reference)
```

So it fails while running the official test suite.

**Comment by mpapierski** [comment]
@ttk2 I just ran it locally with `TARGET=arm-unknown-linux-gnueabi` and works for me locally. Any idea why it might fail on travis?

**Comment by jkilpatr** [comment]
there's probably simply no provided compiler for those architectures in the default repos of the travis ubuntu distro.

**Comment by mpapierski** [comment]
@jkilpatr `cross` wraps cross compilers inside its docker image, so the actual commands would be the same locally and on travis. Maybe the travis image itself is somehow capped?

**Pull request merged**
